package com.ljx.blog.pojo;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * null
 * @TableName t_comment
 */
@Data
public class TComment implements Serializable {

    private Long id;

    /**
     * 昵称
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private String nickname;

    /**
     * 邮箱
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private String email;

    /**
     * 评论内容
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private String content;

    /**
     * 头像
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private String avatar;

    /**
     * 创建时间
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private Date createTime;

    /**
     * 博客编号
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private Long blogId;

    /**
     * 
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private Long parentCommentId;

    /**
     * 
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private Integer admincomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_comment
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private static final long serialVersionUID = 1L;
}