package com.ljx.blog.pojo;

import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName t_type
 */
@Data
public class TType implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private Long id;

    /**
     * 
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_type
     *
     * @mbg.generated 2021-03-07 18:20:26
     */
    private static final long serialVersionUID = 1L;
}